version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    # Remove or comment out the volumes section for production build
    # volumes:
    #   - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MINDSDB_HOST=cloud.mindsdb.com
      - MINDSDB_USER=${MINDSDB_USER}
      - MINDSDB_PASSWORD=${MINDSDB_PASSWORD}
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/hello"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge 